### ISSUE TITLE
The issue..

### ISSUE THREAD

**Issue by TheMegaLeo** [FreezyEx/Deflationary-Token#1]
Hello! Do you maybe know how could i fix this?? TheMegaLeo#7734 this is my discord if you could also possibly add me I am really bad with these.. But I'm hoping u could help me. 

![issue](https://user-images.githubusercontent.com/84332019/118502793-522b2200-b72a-11eb-82c5-67025cd9f79e.png)

**Comment by FreezyEx** [comment]
This is only a syntax error. Please don't open issue for this problems

**Comment by TheMegaLeo** [comment]
@FreezyEx Please could you still help me out cuz I have 0 idea how to fix it?

**Comment by TheMegaLeo** [comment]
If you don't want to do it here add me on dc, but I'd really appreciate if you could help me out.
