### ISSUE TITLE
Supply

### ISSUE THREAD

**Issue by TheMegaLeo** [FreezyEx/Deflationary-Token#2]
Question, after deploying my coin I've got no supply how am i supposed to get my dev wallet ?

**Comment by FreezyEx** [comment]
I think you choosed the wrong contract in Deploy section

Il giorno lun 17 mag 2021 alle ore 18:19 TheMegaLeo <
***@***.***> ha scritto:

**Comment by TheMegaLeo** [comment]
Could you possibly explain what should I do, I have no expirience

**Comment by Banger67** [comment]
Hey man, I'm having some issues in remix with the contract and it's giving me many errors

**Comment by FreezyEx** [comment]
https://forum.openzeppelin.com/t/how-to-fix-gas-estimation-errored-with-the-following-message-see-below-safemoon-fork/8577

Il giorno lun 17 mag 2021 alle ore 20:16 Banger67 ***@***.***>
ha scritto:
