### ISSUE TITLE
Smart contract deploy error

### ISSUE THREAD

**Issue by S1ipKn0T** [FreezyEx/Deflationary-Token#4]
Hi, I’m a beginner at creating contracts, I’ve error when I deploy your contract code with truffle and ganache-cli:

"Owo" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.

> this is my constructor code:

`
constructor (address payable charityWalletAddress) public {
        _charityWalletAddress = charityWalletAddress;
        _rOwned[_msgSender()] = _rTotal;

        IUniswapV2Router02 _uniswapV2Router = IUniswapV2Router02(0x10ED43C718714eb63d5aA57B78B54704E256024E);
        // pancakeswapv2 for BSC network
        // Create a uniswap pair for this new token
        uniswapV2Pair = IUniswapV2Factory(_uniswapV2Router.factory())
        .createPair(address(this), _uniswapV2Router.WETH());

        // set the rest of the contract variables
        uniswapV2Router = _uniswapV2Router;

        // Exclude owner and this contract from fee
        _isExcludedFromFee[owner()] = true;
        _isExcludedFromFee[address(this)] = true;

        emit Transfer(address(0), _msgSender(), _tTotal);
    }
`

> my 3_deploy.js

`const Owo = artifacts.require("Owo");

module.exports = async function (deployer) {
    const accounts = await web3.eth.getAccounts()
    await deployer.deploy(Owo, accounts[0]);
};`

what's the problem mate? If possible, can you send me a comfortable deploy.js file for this contract or anything I need? Thanks.

**Comment by FreezyEx** [comment]
You can deploy easier with remix. You must give an address as parameter in constructor
