### ISSUE TITLE
Fees?

### ISSUE THREAD

**Issue by voriand** [FreezyEx/Deflationary-Token#7]
Hi!

Thank you very much for this great code. I'm just a little bit confused regarding the default fees:

```
    string private _name = "Name COIN";
    string private _symbol = "Name";
    uint8 private _decimals = 18;
    
    uint256 public _taxFee = 3;
    uint256 private _previousTaxFee = _taxFee;
    
    uint256 public _liquidityFee = 3;
    uint256 private _previousLiquidityFee = _liquidityFee;

    uint256 public _burnFee = 3;
    uint256 private _previousBurnFee = _burnFee;

    uint256 public _charityFee = 5;
    address public charityWallet = 0x4eF9A651F8656DEf8454178406eEae16FB7Ca458;
    uint256 private _previouscharityFee = _charityFee;
```

So the default is 3% tax fee, 3% liquidity fee, 3% burn fee and 5% charity fee, so all together 14%? Which one of these is exactly the holders reward fee and what is then the 4th one?

Sorry, I'm a little bit new to this :)

**Comment by FreezyEx** [comment]
taxFee = holders reward
and charity is for charity wallet
